version: '3'

services:

  webserver:
    image: nginx:1.13.9-alpine
    container_name: schemaspy_nginx
    volumes:
      - ./html:/var/www/html:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8081:80"
    environment:
      - LANG=ja_JP.UTF-8
      - TZ=Asia/Tokyo
    command: "nginx -g 'daemon off;'"

  schemaspy:
    build: .
    image: treetips/schemaspy-mysql
    container_name: schemaspy_core
    volumes:
      - ./html:/app/html:rw
      - ./schemaspy.properties:/app/schemaspy.properties:ro
    environment:
      - LANG=ja_JP.UTF-8
      - TZ=Asia/Tokyo
    working_dir: "/app"
    command: "java -jar schemaspy.jar"
